In [8]:
import numpy as np

A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]]) 
D = np.array([[3,-2,-1],[1,2,3]])
v = np.array([3,5,-1,4])
u = np.array([6,2,-3,5])

In [5]:
np.sqrt(np.dot(u,u))

8.602325267042627

In [6]:
np.linalg.norm(u)

8.602325267042627

In [9]:
B.dot(A)

array([[-1, -5, -1],
       [ 2,  7,  4]])

In [10]:
np.dot(B,A)

array([[-1, -5, -1],
       [ 2,  7,  4]])

In [11]:
np.add(np.transpose(C),3*D)

array([[14,  3,  3],
       [ 2,  7,  9]])

In [12]:
C.T + 3*D

array([[14,  3,  3],
       [ 2,  7,  9]])