In [5]:
import pickle
import pandas as pd
import numpy as np

import statsmodels.api as sm
import statsmodels.formula.api as smf
import patsy

import seaborn as sns
import matplotlib.pyplot as plt
import sklearn.datasets

from sklearn.linear_model import LinearRegression, Lasso, LassoCV, Ridge, RidgeCV
from sklearn.model_selection import cross_val_score, KFold, train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline

%matplotlib inline

## Day 1

In [50]:
# Write a program that prints the numbers from 1 to 100. But 
# for multiples of three print “Fizz” instead of the number 
# and for the multiples of five print “Buzz”. For numbers 
# which are multiples of both three and five print “FizzBuzz”.

def fizzbuzz_hundred():
    return ['FizzBuzz' if x%3==0 and x%5==0
            else 'Fizz' if x%3==0
            else 'Buzz' if x%5==0
            else x for x in list(range(1,101))]


In [54]:
# Write a function that takes a list of names 
# and returns a list of lists of tuples representing pairs. 
# (Assume an even number of names, all distinct.) For example:
# pairs_for(['Andrea', 'Bob', 'Cassandra', 'Doug'])

import random

def create_pairs(names_list):
    '''
    Takes a list of names and returns 
    a list of lists of tuples
    representing pairs.
    '''
    pairs = []
    while len(names_list)>1:
        indx1 = random.randrange(0, len(names_list))
        name1 = names_list.pop(indx1)
        
        indx2 = random.randrange(0, len(names_list))
        name2 = names_list.pop(indx2)
    
        pairs.append((name1,name2))

    return pairs

In [58]:
# Testing create_pairs above function

test_list = ['Andrea', 'Bob', 'Cassandra', 'Doug','Garrett','Marcie']

create_pairs(test_list)


[('Doug', 'Marcie'), ('Garrett', 'Bob'), ('Andrea', 'Cassandra')]

## Day 2

In [1]:
# What is the largest prime factor of the number 600851475143 ?

def largest_prime_factor(num):
    i=1
    primes = []
    while(i<=num):
        k=0
        if(num%i==0):
            j=1
            while(j<=i):
                if(num%j==0):
                    k=k+1
                j=j+1
            if(k==2):
                primes.append(i)
        i=i+1
    return (max(primes))

## Day 3

In [21]:
# Given a string, write a function to reverse it. Do this using a loop, if possible.
# Example: reverseString('abcdef') will return 'fedcba'
# Example: reverseString('moon') will return 'noom'

str1 = 'abcdef'

#this works but is it technically a loop?
def reverse_str(string):
    return string[::-1]

reverse_str(str1)

'fedcba'

In [22]:
#here it is with a loop...but seems more complicated?

def reverse_str_v2(string):
    let_list = []
    for x in range(0,len(string)):
        let_list.insert(0,string[x])
    return(''.join(let_list))

reverse_str_v2(str1)

'fedcba'

In [ ]:
# PROBLEM 2
# Sal's classroom has a bag of alphabet magnets. She wants to know 
# if she can spell her friend's name using the letters in the bag. 
# Write a function that will take a list of letters and a name and 
# print out yes if the name can be spelled and no otherwise.

# Example 1: CanYouSpell(['y','n','p','g','n','l'],"lynn") would print YES
# Example 2: CanYouSpell(['y','n','p','g','l'],"lynn") would print NO

## Day 4

In [103]:
# Write a function that takes in a number between 1 and 100 
# and tries to guess it. Based on whether a guess is larger 
# or smaller than the input number, the code would come up 
# with a new guess until it gets it right.

def guess_my_num(number):
    guess = random.randint(1,100)
    count = 0
    while guess != number:
        count += 1
        if guess > number:
            guess -= 1
            guess = random.randint(1, guess)
        else:
            guess += 1
            guess = random.randint(guess, 100)
    return f'I got it right in {count} tries.'
    

In [106]:
# Testing guess_my_num function

guess_my_num(87)

'I got it right in 59 tries.'

In [14]:
# Find the thirteen adjacent digits in a given 
# 1000-digit number that have the greatest product. 
# What is the value of this product?

thous_digit_num = \
'''73167176531330624919225119674426574742355349194934\
96983520312774506326239578318016984801869478851843\
85861560789112949495459501737958331952853208805511\
12540698747158523863050715693290963295227443043557\
66896648950445244523161731856403098711121722383113\
62229893423380308135336276614282806444486645238749\
30358907296290491560440772390713810515859307960866\
70172427121883998797908792274921901699720888093776\
65727333001053367881220235421809751254540594752243\
52584907711670556013604839586446706324415722155397\
53697817977846174064955149290862569321978468622482\
83972241375657056057490261407972968652414535100474\
82166370484403199890008895243450658541227588666881\
16427171479924442928230863465674813919123162824586\
17866458359124566529476545682848912883142607690042\
24219022671055626321111109370544217506941658960408\
07198403850962455444362981230987879927244284909188\
84580156166097919133875499200524063689912560717606\
05886116467109405077541002256983155200055935729725\
71636269561882670428252483600823257530420752963450\
'''

#exclude if includes zeros
import numpy as np

# version as asked to just show product result
def greatest_product(number,adjacent_digits):
    thous_list = list(number)
    products_list = []
    for i in range(0,987):
        if '0' not in thous_list[i:i+adjacent_digits+1]:
            numbers = [int(x) for x in thous_list[i:i+adjacent_digits+1]]
            product = np.prod(numbers)
            products_list.append(product)
    return (max(products_list))


#test of function above


greatest_product(thous_digit_num,13)

70573265280

In [15]:
# version to also show numbers to get to product
import timeit

def greatest_product_v2(number,adjacent_digits):
    thous_list = list(number)
    products_dict = {}
    for i in range(0,987):
        if '0' not in thous_list[i:i+adjacent_digits+1]:
            numbers = [int(x) for x in thous_list[i:i+adjacent_digits+1]]
            product = np.prod(numbers)
            products_dict[product] = numbers
    return (f'{max(products_dict)}, the product of {products_dict[max(products_dict)]}')

#test of function above

greatest_product_v2(thous_digit_num,13)

'70573265280, the product of [9, 7, 5, 3, 6, 9, 7, 8, 1, 7, 9, 7, 7, 8]'

## Week 2: Thursday

In [8]:
import numpy as np

In [ ]:
X = [[5,3,7],
     [2,4,1]]

In [ ]:
y = [537,241]

In [9]:
X = np.array[[2,0]] 

TypeError: 'builtin_function_or_method' object is not subscriptable

In [13]:
np.array([2,0])

array([2, 0])

In [17]:
X = np.array([[2, 4]])
w = np.array([0,2])

In [18]:
np.dot(X,w)

array([8])

In [29]:
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [1]:
26**6

308915776

In [2]:
52*51*50**49*48/5!

22612312022829428315162658691406250000000000000000000000000000000000000000000000000000000

In [ ]:
6!/6**6

### WEEK 3: Day 2

In [12]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

In [14]:
type(sklearn.datasets.load_diabetes())

sklearn.utils.Bunch

In [15]:
diabetes = load_diabetes()

In [16]:
X, y = sklearn.datasets

In [17]:
data1

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019908 -0.017646   151.0  
1   -0.039493 -0.068330 -0.092204    75.0  
2   -0.002592  0.002864 -0.025930   141.0  
3    0.034309  0.022692 -0.009362   206.0  
4   -0.002592 -0.031991 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018118  0.044485   104.0  
439 -0.011080 -0.046879  0.015491   132.0  
440  0.026560  0.044528 -0.025930   220.0  
441 -0.039493 -0.004220  0.003064    57.0  

[442 rows x 11 columns]

In [18]:
type(data1)

pandas.core.frame.DataFrame